[project]
name = "train"
version = "0.1.0"
description = "Train model on MNIST data"
dependencies = [
  "numpy == 2.2.2",
  "torch == 2.6.0",
  "onnx == 1.17.0",
]
requires-python = ">=3.11"

[project.scripts]
train = "train.main:main"
